### ISSUE TITLE
Annoying 'Long json object' baltop update warning in console

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomEconomy#24]
![Annotation 2020-04-06 183250](https://user-images.githubusercontent.com/59464084/78549507-150d1480-7835-11ea-9b61-34d61b123016.png)

**Comment by lokka30** [comment]
Log supplied by another user
```
[14:51:58 WARN]: java.lang.ClassCastException: class java.lang.Long cannot be cast to class org.json.simple.JSONObject (java.lang.Long is in module java.base of loader 'bootstrap'; org.json.simple.JSONObject is in unnamed module of loader 'app')
[14:51:58 WARN]: at io.github.lokka30.phantomeconomy.BaltopUpdater.update(BaltopUpdater.java:35)
[14:51:58 WARN]: at io.github.lokka30.phantomeconomy.PhantomEconomy$1.run(PhantomEconomy.java:73)
[14:51:58 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:51:58 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[14:51:58 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[14:51:58 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[14:51:58 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[14:51:58 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[14:51:58 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by lokka30** [comment]
I remember I changed Map to HashMap, maybe going back to Map will fix it?

**Comment by lokka30** [comment]
Yep doing the above fixed it.

**Comment by lokka30** [comment]
My testing proved incorrect
Apparently its still pooped

**Comment by lokka30** [comment]
Haven't received any reports nor have I experienced this issue since the 27 days it has been since I last saw this happening.
Closing the issue.
Will reopen if anyone else comes across this.
This baltop system will be gone in v2 as well due to the use of databases.
