### ISSUE TITLE
No class found

### ISSUE THREAD

**Issue by yixi7994498** [lokka30/PhantomEconomy#30]
[06:23:54] [Server thread/ERROR]: Error occurred while enabling PhantomEconomy v1.9.8-RELEASE (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/util/Consumer
	at io.github.lokka30.phantomeconomy.PhantomEconomy.checkUpdates(PhantomEconomy.java:225) ~[?:?]
	at io.github.lokka30.phantomeconomy.PhantomEconomy.onEnable(PhantomEconomy.java:88) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.Consumer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 10 more

And how to get the money? like {money}?

**Comment by lokka30** [comment]
Maybe the auto updater is only for newer versions, try disable that and see if the error goes away.

For 'how to get the money', do you mean the money placeholder? If so, are you trying to get the placeholders in PhantomEconomy's messages or other plugin's messages?

**Comment by lokka30** [comment]
Issue closed due to 1 week inactivity.
